CREATE DATABASE vaccination_db;

USE vaccination_db;

CREATE TABLE coverage (
    coverage_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    `GROUP` VARCHAR(50),
    CODE VARCHAR(10),
    NAME VARCHAR(150),
    YEAR INT,
    ANTIGEN VARCHAR(50),
    ANTIGEN_DESCRIPTION VARCHAR(255),
    COVERAGE_CATEGORY VARCHAR(100),
    COVERAGE_CATEGORY_DESCRIPTION VARCHAR(255),
    TARGET_NUMBER BIGINT,
    DOSES BIGINT,
    COVERAGE DECIMAL(8,2)
);

CREATE TABLE incidence_rate (
    incidence_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    `GROUP` VARCHAR(50),
    CODE VARCHAR(10),
    NAME VARCHAR(150),
    YEAR INT,
    DISEASE VARCHAR(50),
    DISEASE_DESCRIPTION VARCHAR(255),
    DENOMINATOR BIGINT,
    INCIDENCE_RATE DECIMAL(12,4)
);

CREATE TABLE reported_cases (
    case_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    `GROUP` VARCHAR(50),
    CODE VARCHAR(10),
    NAME VARCHAR(150),
    YEAR INT,
    DISEASE VARCHAR(50),
    DISEASE_DESCRIPTION VARCHAR(255),
    CASES BIGINT
);

CREATE TABLE vaccine_introduction (
    introduction_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    ISO_3_CODE CHAR(3),
    COUNTRYNAME VARCHAR(150),
    WHO_REGION VARCHAR(100),
    YEAR INT,
    DESCRIPTION VARCHAR(255),
    INTRO VARCHAR(50)
);

CREATE TABLE vaccine_schedule (
    schedule_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    ISO_3_CODE CHAR(3),
    COUNTRYNAME VARCHAR(150),
    WHO_REGION VARCHAR(100),
    YEAR INT,
    VACCINECODE VARCHAR(50),
    VACCINE_DESCRIPTION VARCHAR(255),
    SCHEDULEROUNDS VARCHAR(50),
    TARGETPOP VARCHAR(100),
    TARGETPOP_DESCRIPTION VARCHAR(255),
    GEOAREA VARCHAR(255),
    AGEADMINISTERED VARCHAR(100),
    SOURCECOMMENT TEXT
);


CREATE TABLE coverage (
    coverage_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    `GROUP` VARCHAR(50),
    CODE VARCHAR(10),
    NAME VARCHAR(150),
    YEAR INT,
    ANTIGEN VARCHAR(50),
    ANTIGEN_DESCRIPTION VARCHAR(255),
    COVERAGE_CATEGORY VARCHAR(100),
    COVERAGE_CATEGORY_DESCRIPTION VARCHAR(255),
    TARGET_NUMBER BIGINT,
    DOSES BIGINT,
    COVERAGE DECIMAL(8,2)
);

CREATE TABLE incidence_rate (
    incidence_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    `GROUP` VARCHAR(50),
    CODE VARCHAR(10),
    NAME VARCHAR(150),
    YEAR INT,
    DISEASE VARCHAR(50),
    DISEASE_DESCRIPTION VARCHAR(255),
    DENOMINATOR BIGINT,
    INCIDENCE_RATE DECIMAL(12,4)
);

CREATE TABLE reported_cases (
    case_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    `GROUP` VARCHAR(50),
    CODE VARCHAR(10),
    NAME VARCHAR(150),
    YEAR INT,
    DISEASE VARCHAR(50),
    DISEASE_DESCRIPTION VARCHAR(255),
    CASES BIGINT
);

CREATE TABLE vaccine_introduction (
    introduction_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    ISO_3_CODE CHAR(3),
    COUNTRYNAME VARCHAR(150),
    WHO_REGION VARCHAR(100),
    YEAR INT,
    DESCRIPTION VARCHAR(255),
    INTRO VARCHAR(50)
);

ALTER TABLE coverage
MODIFY TARGET_NUMBER BIGINT NULL,
MODIFY DOSES BIGINT NULL;

DESCRIBE coverage;

SELECT COUNT(*) AS total_records
FROM incidence_rate;

ALTER TABLE incidence_rate
MODIFY DENOMINATOR VARCHAR(100) NULL;

SHOW VARIABLES LIKE 'local_infile';
SET GLOBAL local_infile = 1;
SHOW VARIABLES LIKE 'local_infile';


LOAD DATA LOCAL INFILE '/Users/anushka/Downloads/Vaccination project/schedule_mysql.csv'
INTO TABLE vaccine_schedule
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(ISO_3_CODE, COUNTRYNAME, WHO_REGION, YEAR, VACCINECODE,
 VACCINE_DESCRIPTION, SCHEDULEROUNDS, TARGETPOP,
 TARGETPOP_DESCRIPTION, GEOAREA, AGEADMINISTERED, SOURCECOMMENT);
 

SELECT 'coverage' AS table_name, COUNT(*) AS records FROM coverage
UNION ALL
SELECT 'incidence_rate', COUNT(*) FROM incidence_rate
UNION ALL
SELECT 'reported_cases', COUNT(*) FROM reported_cases
UNION ALL
SELECT 'vaccine_introduction', COUNT(*) FROM vaccine_introduction
UNION ALL
SELECT 'vaccine_schedule', COUNT(*) FROM vaccine_schedule;

USE vaccination_db;
TRUNCATE TABLE coverage;

SELECT COUNT(*) AS coverage_records
FROM coverage;

SHOW VARIABLES LIKE 'secure_file_priv';


LOAD DATA INFILE '/Users/anushka/Downloads/Vaccination project/coverage_clean.csv'
INTO TABLE coverage
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(@grp, @code, @name, @year, @antigen, @antigen_desc,
 @cat, @cat_desc, @target, @doses, @coverage)
SET
    `GROUP` = NULLIF(@grp, ''),
    CODE = NULLIF(@code, ''),
    NAME = NULLIF(@name, ''),
    YEAR = NULLIF(@year, ''),
    ANTIGEN = NULLIF(@antigen, ''),
    ANTIGEN_DESCRIPTION = NULLIF(@antigen_desc, ''),
    COVERAGE_CATEGORY = NULLIF(@cat, ''),
    COVERAGE_CATEGORY_DESCRIPTION = NULLIF(@cat_desc, ''),
    TARGET_NUMBER = NULLIF(@target, ''),
    DOSES = NULLIF(@doses, ''),
    COVERAGE = NULLIF(@coverage, '');